# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Complexe
                                 A QGIS plugin
 Assistant complexe
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QObject, QEvent, QTimer
from PyQt5.QtGui import QIcon, QPixmap, QStandardItem, QStandardItemModel
from PyQt5.QtWidgets import QDialog, QListWidgetItem, QPushButton, QListView, QVBoxLayout, \
    QAbstractItemView, QTableView
from PyQt5.uic import loadUi
import json

# Initialize Qt resources from file resources.py
# Import the code for the dialog

SEPARATION_TOOLTIP = "\t\U0001F846\t"

import os.path
from .layout_fluide import *

class FiltreClicDroit(QObject):
    def __init__(self, class_parent):
        super().__init__()
        self.class_parent = class_parent

    def eventFilter(self,obj,event):
        if event.type() == QEvent.MouseButtonPress and event.button() == Qt.RightButton:
            self.class_parent.show_dlg_config_btn(obj)
            return True  # on consomme l’événement (empêche le clic normal).
        return False

class JeuxAttributs:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        # choix de l'icône

        self.taille_icone_dans_listview = None
        self.taille_btn = None
        self.button_ok = None
        self.listview = None
        self.new_index_btn = None

        self.valeur_btn_sel = None
        self.sstype_btn_sel = None

        self.dlg_sel_champ_val = None
        self.dlg_sel_champ_val_AUTRE = None
        self.dlg_config_btn = None
        self.dlg = None
        self.dlg_icon = None

        self.clicked_button = None

        self.iface = iface
        self.layer = None
        self.dico_layer_attrval = {}
        self.liste_filtres = []
        self.model = None
        self.pathiconbtnclicked = None
        self.pathjson = os.path.join(os.path.dirname(__file__),"config", "config_btn.json")
        self.pathjsonparametre = os.path.join(os.path.dirname(__file__), "config", "parametres.json")
        self.pathicon_config = os.path.join(os.path.dirname(__file__), "icons", "config.png")
        self.pathicon_interface = os.path.join(os.path.dirname(__file__), "icons", "icon_principal.png")
        self.path_repicon_btn = os.path.join(os.path.dirname(__file__),"config", "icons_btn")

        self.layout_boutons = None

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    def show_dlg_config_btn(self,btn):


        self.clicked_button = btn
        # recuperation des infos du boutons cliqué grace au tooltip qui contient : sstype, valeur
        tooltip = self.clicked_button.toolTip()
        self.sstype_btn_sel, self.valeur_btn_sel = tooltip.split(SEPARATION_TOOLTIP)

        self.dlg_config_btn.setWindowTitle("Paramétrage des boutons et des actions associés")
        self.dlg_config_btn.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        # le nom est récupéré à partir du tooltip
        # car si l'icône est renseigné le bouton perd son nom
        self.dlg_config_btn.lineEditNomBtn.setText(btn.text())

        # ****************NOM BOUTON*****************
        nom_btn = ""
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour du nom du bouton
                nom_btn = item["nom_btn"]
                break
        self.dlg_config_btn.lineEditNomBtn.setText(nom_btn)

        # ****************ICONE**********************
        icon_str = ""
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                    # Exemple : mise à jour du nom du bouton
                    icon_str = item["icon"]
                    break
        self.dlg_config_btn.lineEdit_icone.setText(icon_str)
        path = os.path.join(self.path_repicon_btn,icon_str)
        pixmap = QPixmap(path)
        pixmap = pixmap.scaled(20, 20, Qt.KeepAspectRatio, Qt.SmoothTransformation)
        self.dlg_config_btn.label_icon_sel.setPixmap(pixmap)

        # ***************AUTRE VALEUR*********************
        autre_sstype_valeur = {}
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour du nom du bouton
                autre_sstype_valeur = item["autre_valeur"]
                break
        model = self.dlg_config_btn.tableView_autre_valeur.model()
        # il faut vider le tableview avant d'ajouter
        model.clear()
        for sstype_autre, valeur_autre in autre_sstype_valeur.items():
            model.appendRow([QStandardItem(sstype_autre), QStandardItem(valeur_autre)])
        self.dlg_config_btn.tableView_autre_valeur.setColumnWidth(0, 200)
        self.dlg_config_btn.tableView_autre_valeur.setColumnWidth(1, 100)

        # ****************** config widget déplacement
        nb_btn_tolayer = len(self.dico_layer_attrval[self.layer.name()])
        self.dlg_config_btn.spinBoxPosition.setRange(1,nb_btn_tolayer)
        self.dlg_config_btn.spinBoxPosition.setValue(self.getposbtn()+1)

        sstype_str = f"<span style='color: red'><b>{self.sstype_btn_sel}</b></span>"
        self.dlg_config_btn.label_ss_type.setText(sstype_str)
        valeur_str = f"<span style='color: red'><b>{self.valeur_btn_sel}</b></span>"
        self.dlg_config_btn.label_valeur.setText(valeur_str)
        self.dlg_config_btn.label_fleche.setText(SEPARATION_TOOLTIP)

        self.dlg_config_btn.radioButtonText.setChecked(True)
        self.dlg_config_btn.labelAvertissement.setText("")


        try:
            self.dlg_config_btn.pushButton_choix_icon.clicked.disconnect()
        except TypeError:
            pass
        self.dlg_config_btn.pushButton_choix_icon.clicked.connect(lambda: self.choix_icone(self.sstype_btn_sel, self.valeur_btn_sel))
        self.dlg_config_btn.lineEditNomBtn.textChanged.connect(self.nom_btn_change)

        self.dlg_config_btn.exec_()

    def getposbtn(self):
        index_btn_sel = next(
            (i for i, item in enumerate(self.dico_layer_attrval[self.layer.name()])
             if item["sous_type"] == self.sstype_btn_sel and item["valeur"] == self.valeur_btn_sel),
            None
        )
        # (+1) la premiere position est 1, pas 0
        return index_btn_sel

    def spinbox_change(self, value):
        self.new_index_btn = value

    def suppr_ligne_tableview(self):
        # recuperation de la selection
        model = self.dlg_config_btn.tableView_autre_valeur.model()
        selection_model = self.dlg_config_btn.tableView_autre_valeur.selectionModel()
        # index des lignes sélectionnées
        selected_indexes = selection_model.selectedRows()

        for index in selected_indexes:
            row = index.row()
            model.removeRow(row)

        # maj du dictionnaire
        self.clicked_button.toolTip()
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour du nom du bouton
                item["autre_valeur"] = self.convert_tableview_to_dico()
                break
        self.save_json()

    def deplace_btn(self):
        # print("deplace a l'index : index = ",self.new_index_btn)
        dico_avant = self.dico_layer_attrval[self.layer.name()]

        # arrangement du dico "-1" car la premiere position est à 0 et non 1
        new_index = self.new_index_btn -1
        # recuperation de la position du bouton sélectionné à partir du json
        index_btn_sel = self.getposbtn()
        # Échange des deux positions
        dico_avant[new_index], dico_avant[index_btn_sel] = (
            dico_avant[index_btn_sel],
            dico_avant[new_index],
        )
        # sauvegarde
        self.dico_layer_attrval[self.layer.name()] = dico_avant
        self.save_json()

    def nom_btn_change(self):
        if self.dlg_config_btn.lineEditNomBtn.text() != "":
            self.dlg_config_btn.labelAvertissement.setText("")

    def valide_config_btn(self,sstype,valeur):
        print(f"valide_config_btn : {sstype}, {valeur}")
        self.valide_nom_btn(sstype,valeur)

        if self.dlg_config_btn.radioButtonText.isChecked():
            if self.dlg_config_btn.lineEditNomBtn.text() == "":
                self.dlg_config_btn.labelAvertissement.setText("<span style='color: red'><b>Le nom du bouton est vide</b></span>")
                return
            else:
                self.clicked_button.setText(self.dlg_config_btn.lineEditNomBtn.text())

        elif self.dlg_config_btn.radioButtonIcon.isChecked():
            if self.pathiconbtnclicked is None:
                self.dlg_config_btn.labelAvertissement.setText(
                    "<span style='color: red'><b>Aucune icône n'est sélectionnée</b></span>")
                return
            else:
                self.clicked_button.setText("")
                self.clicked_button.setIcon(QIcon(self.pathiconbtnclicked))
            # self.clicked_button.setFixedWidth(20)
        self.save_json()
        self.clear_layout(self.layout_boutons)
        self.liste_filtres = []
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()
        self.dlg_config_btn.close()

    def choix_autre_valeur(self):
        self.dlg_sel_champ_val_AUTRE.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        self.dlg_sel_champ_val_AUTRE.comboBoxchamps.clear()
        self.dlg_sel_champ_val_AUTRE.listattributs.clear()

        # on masque le lineedit de la taille des boutons
        self.dlg_sel_champ_val_AUTRE.lineEditTailleBtn.hide()
        self.dlg_sel_champ_val_AUTRE.label_taille_btn.hide()

        self.init_combo_choix_champ(self.dlg_sel_champ_val_AUTRE)
        self.dlg_sel_champ_val_AUTRE.exec_()

    def valide_nom_btn(self,sstype,valeur):
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == sstype and item.get("valeur") == valeur:
                # Exemple : mise à jour du nom du bouton
                item["nom_btn"] = self.dlg_config_btn.lineEditNomBtn.text()
                break

    def valide_icone(self,sstype,valeur):
        # sauvegarde de l'icône le dictionnaire
        if self.pathiconbtnclicked:
            filico = os.path.basename(self.pathiconbtnclicked)
            self.dlg_config_btn.lineEdit_icone.setText(filico)
        else:
            filico = ""
        # ajout de l'icône dans le dictionnaire et suppression du nom
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == sstype and item.get("valeur") == valeur:
                # Exemple : mise à jour de l'icône du bouton
                item["icon"] = filico
                # item["nom_btn"] = ""
                break
        # on actualise l'icône a afficher apres le nom de l'icône
        # path = os.path.join(self.path_repicon_btn, icon_str)
        pixmap = QPixmap(self.pathiconbtnclicked)
        pixmap = pixmap.scaled(30, 30, Qt.KeepAspectRatio, Qt.SmoothTransformation)
        self.dlg_config_btn.label_icon_sel.setPixmap(pixmap)

    def valide_dlg_icone(self,sstype,valeur):
        self.valide_icone(sstype, valeur)
        self.dlg_icon.close()

    def choix_icone(self,sstype,valeur):
        # interface
        self.dlg_icon = QDialog()
        self.dlg_icon.setWindowTitle("Choisir une icône...")
        self.dlg_icon.setWindowIcon(QIcon(self.pathicon_interface))
        self.dlg_icon.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        layout = QVBoxLayout()
        self.listview = QListView()
        self.button_ok = QPushButton("Valider")
        layout.addWidget(self.listview)
        layout.addWidget(self.button_ok)
        self.dlg_icon.setLayout(layout)
        # self.button_ok.clicked.connect(lambda:self.valider_icone(sstype,valeur))
        self.button_ok.clicked.connect(lambda:self.valide_dlg_icone(sstype,valeur))

        self.init_listview_icones()

        self.dlg_icon.exec_()

    def init_listview_icones(self):
        self.model = QStandardItemModel()
        self.listview.setModel(self.model)
        self.listview.setViewMode(QListView.IconMode)
        self.listview.setSelectionMode(QListView.SingleSelection)
        for filename in os.listdir(self.path_repicon_btn):
            if filename.lower().endswith(".ico"):
                path = os.path.join(self.path_repicon_btn, filename)
                taille = int(self.taille_icone_dans_listview)
                pixmap = QPixmap(path).scaled(taille, taille)
                # pixmap = QPixmap(path)
                icon = QIcon(pixmap)

                item = QStandardItem(icon, filename)
                item.setData(path)  # On garde le chemin complet
                item.setEditable(False)
                self.model.appendRow(item)

        self.listview.clicked.connect(self.get_icon_path_selected)

    def get_icon_path_selected(self, index):
        """Quand l'utilisateur clique sur une icône."""
        self.pathiconbtnclicked = self.model.itemFromIndex(index).data()

    # ajout de tous les champs possible dans le combobox
    def init_combo_choix_champ(self,dlg):
        self.layer = self.iface.activeLayer()
        for field in self.layer.fields():
            index = self.layer.fields().indexOf(field.name())
            widget_type = self.get_type_champ(index)
            if widget_type == "ValueMap":
                # self.dlg_selattributs.comboBoxchamps.addItem(field.name())4
                dlg.comboBoxchamps.addItem(field.name())

    # initialise toutes les valeurs en fonction du champ sélectionné
    def init_list_valeur(self,champ,dlg):
        # pk faire ce test !!
        if champ == "":
            return

        list_sstype_val = self.get_sstype_valeur_from_dico(self.layer.name(),self.dico_layer_attrval)

        dlg.listattributs.clear()

        layer_field = self.layer.fields().field(champ)
        # Vérifier le type d’éditeur liste de dico (troncon_hydro) ou dico (autre)
        # pourquoi la structure est différente ???
        editor_setup = layer_field.editorWidgetSetup()
        valeurs_possibles = []
        for v in editor_setup.config().values():
            # cas de liste de dictionnaire → on dépile
            if isinstance(v, dict):
                valeurs_possibles.extend(v.values())  # récupérer les vrais libellés
            # Cas où c'est une liste : cf. tronçon hydro
            elif isinstance(v, list):
                # Cas d’une liste → on ajoute chaque élément
                for elem in v:
                    if isinstance(elem, dict):
                        # Cas d’une liste de dictionnaires
                        valeurs_possibles.extend(elem.values())
                    else:
                        valeurs_possibles.append(elem)
            else:
                valeurs_possibles.append(v)

        for val in valeurs_possibles:
            item = QListWidgetItem(val)
            item.setCheckState(Qt.Unchecked)
            if dlg == self.dlg_sel_champ_val:
                if (champ,val) in list_sstype_val:
                    item.setCheckState(Qt.Checked)
            dlg.listattributs.addItem(item)
            if dlg == self.dlg_sel_champ_val_AUTRE:
                self.dlg_sel_champ_val_AUTRE.listattributs.itemChanged.connect(self.on_item_changed)

    def on_item_changed(self, changed_item):
        """Empêche d'avoir plusieurs cases cochées."""
        if changed_item.checkState():
            # Décoche toutes les autres
            for i in range(self.dlg_sel_champ_val_AUTRE.listattributs.count()):
                item = self.dlg_sel_champ_val_AUTRE.listattributs.item(i)
                if item is not changed_item and item.checkState():
                    item.setCheckState(0)

    def get_attrs_coches(self,dlg,coche = True):
        val_coche = []
        if coche:
            bcoche = Qt.Checked
        else:
            bcoche = Qt.Unchecked
        for i in range(dlg.listattributs.count()):
            item = dlg.listattributs.item(i)
            if item.checkState() == bcoche:
                val_coche.append(item.text())
        return val_coche

    def show_choix_attr_val(self):
        self.dlg_sel_champ_val.comboBoxchamps.clear()
        self.dlg_sel_champ_val.listattributs.clear()
        self.init_combo_choix_champ(self.dlg_sel_champ_val)

        self.dlg_sel_champ_val.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        self.dlg_sel_champ_val.exec_()

    def change_champ(self,dlg):
        dlg.listattributs.clear()
        champ = dlg.comboBoxchamps.currentText()
        self.init_list_valeur(champ,dlg)

    def get_type_champ(self,index):
        return self.layer.editorWidgetSetup(index).type()

    @staticmethod
    def clear_layout(layout):
        """Supprime tous les widgets d’un QLayout"""
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.setParent(None)
                widget.deleteLater()
            elif item.layout():
                JeuxAttributs.clear_layout(item.layout())

    # ajout du bouton de paramétrage
    def initLayout(self):
        btn_add = QPushButton()
        btn_add.setFixedWidth(self.taille_btn)
        btn_add.setFixedHeight(self.taille_btn)
        pixmap = QPixmap(self.pathicon_config)
        pixmap = pixmap.scaled(self.taille_btn, self.taille_btn, Qt.KeepAspectRatio, Qt.SmoothTransformation)
        icon = QIcon(pixmap)
        btn_add.setIconSize(pixmap.size())
        btn_add.setIcon(icon)

        # self.btn_add.setStyleSheet("background-color: lightblue;")
        btn_add.clicked.connect(self.show_choix_attr_val)

        self.layout_boutons.addWidget(btn_add)

        self.dlg.setLayout(self.layout_boutons)

    def get_sstype_valeur_from_dico(self,layer,dico):
        list_sstype_valeur = []
        for cle , elements in dico.items():
            if cle == layer:
                for item in elements:
                     list_sstype_valeur.append((item.get("sous_type"),item.get("valeur")))
        # liste de tuples
        return list_sstype_valeur

    def get_icon_from_dico(self,layer,sous_type,valeur):
        elements = self.dico_layer_attrval.get(layer, [])
        for item in elements:
            if item.get("sous_type") == sous_type and item.get("valeur") == valeur:
                return item.get("icon", "")
        # Aucun match trouvé → retourne une chaîne vide
        return ""

    def get_nombtn_from_dico(self,layer,sous_type,valeur):
        elements = self.dico_layer_attrval.get(layer, [])
        for item in elements:
            if item.get("sous_type") == sous_type and item.get("valeur") == valeur:
                return item.get("nom_btn", "")
        # Aucun match trouvé → retourne une chaîne vide
        return ""

    def ajout_btn_from_json(self):
        self.liste_filtres = []
        for layer in self.dico_layer_attrval.keys():
            if layer == self.layer.name():
                champ_val = self.get_sstype_valeur_from_dico(self.layer.name(),self.dico_layer_attrval)
                for sstype,valeur in champ_val:
                    icon_str = self.get_icon_from_dico(self.layer.name(),sstype,valeur)
                    path_icon = os.path.join(self.path_repicon_btn, icon_str)
                    nom_json = self.get_nombtn_from_dico(self.layer.name(),sstype,valeur)
                    widget = QPushButton(valeur)
                    widget.setFixedHeight(self.taille_btn)
                    # initialisation du filtre clic droit
                    filtre = FiltreClicDroit(self)
                    self.liste_filtres.append(filtre)
                    widget.installEventFilter(filtre)

                    widget.setToolTip(f"{sstype}{SEPARATION_TOOLTIP}{valeur}")


                    # si icon present dans json on affiche l'icône
                    # et on vide le nom du btn meme s'il est renseigné
                    if icon_str != "":
                        # l'image ne doit etre plus petite que le bouton sinon elle le recouvre
                        # et on ne peut plus cliquer dessus
                        taille_icon = self.taille_btn* 0.85
                        widget.setFixedHeight(self.taille_btn)
                        widget.setFixedWidth(self.taille_btn)
                        pixmap = QPixmap(path_icon)
                        pixmap = pixmap.scaled(int(taille_icon), int(taille_icon), Qt.KeepAspectRatio, Qt.SmoothTransformation)
                        icon = QIcon(pixmap)
                        widget.setIconSize(pixmap.size())
                        widget.setIcon(icon)
                        widget.setText("")
                    else:
                        widget.setText(nom_json)

                    # connexion d'un événement clic pour chaque btn
                    widget.clicked.connect(lambda checked, v=valeur, c=sstype: self.clic_btn(v, c))
                    self.layout_boutons.addWidget(widget)
                    # Recalcule dynamique de la taille du dialog
                    self.layout_boutons.invalidate()
                    self.layout_boutons.activate()
                    # astuce : attendre la fin de la boucle d'événement avant de recalculer la taille
                    QTimer.singleShot(0, self.dlg.adjustSize)

    def inittableview_autre_valeur(self):
        model = QStandardItemModel()
        model.setHorizontalHeaderLabels(["Sous type", "Valeur"])
        self.dlg_config_btn.tableView_autre_valeur.setModel(model)
        # tableview en lecture seule
        self.dlg_config_btn.tableView_autre_valeur.setEditTriggers(QAbstractItemView.NoEditTriggers)

        # sélection de lignes entières
        self.dlg_config_btn.tableView_autre_valeur.setSelectionBehavior(QTableView.SelectRows)
        self.dlg_config_btn.tableView_autre_valeur.setSelectionMode(QTableView.SingleSelection)

    def actualise_autre_val(self):
        # champ — val des "autres"
        sstype_autre = self.dlg_sel_champ_val_AUTRE.comboBoxchamps.currentText()
        attr_coche_autre = self.get_attrs_coches(self.dlg_sel_champ_val_AUTRE)

        # c'est le model qui gere les ajouts, donc on récupère le model associé a la tableview'
        model = self.dlg_config_btn.tableView_autre_valeur.model()

        # Suppression de toutes les lignes correspondant au sstype sélectionné
        # avant d'ajouter la ligne en cours.
        # Car on a droit qu'à une seule ligne de valeur
        # Parcourir les lignes en sens inverse (pour éviter le décalage d'index)
        for row in reversed(range(model.rowCount())):
            index = model.index(row, 0)  # 0 = première colonne
            valeur = model.data(index)
            if valeur == sstype_autre:
                model.removeRow(row)

        # si aucune valeur cochée, on n'ajoute rien
        if not attr_coche_autre:
            return

        # mise à jour du tableview avec la selection
        model.appendRow([QStandardItem(sstype_autre), QStandardItem(attr_coche_autre[0])])

        # sauvegarde dans le dico
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            # [0] car on ne prend que le premier de la liste vu qu'on peut avoir
            # qu'une seule valeur par sous type
            if item.get("sous_type") == self.sstype_btn_sel and item.get("valeur") == self.valeur_btn_sel:
                # Exemple : mise à jour de l'icône du bouton
                item["autre_valeur"] = self.convert_tableview_to_dico()
                break
        self.save_json()

    # renvoie le contenu du tableview des sstype-valeur sous forme de dictionnaire
    def convert_tableview_to_dico(self):
        model = self.dlg_config_btn.tableView_autre_valeur.model()
        data_dict = {}
        for row in range(model.rowCount()):
            # Première colonne : clé
            key = model.data(model.index(row, 0))
            # Deuxième colonne : valeur
            value = model.data(model.index(row, 1))

            if key:  # on évite les clés vides
                data_dict[key] = value

        return data_dict

    def actualise_btn(self):
        sstype = self.dlg_sel_champ_val.comboBoxchamps.currentText()
        valeurs = self.get_attrs_coches(self.dlg_sel_champ_val)

        # Initialise la clé avec une liste vide si absente
        self.dico_layer_attrval.setdefault(self.layer.name(), [])
        champ_attr_a_suppr = {(sstype, attr) for attr in self.get_attrs_coches(self.dlg_sel_champ_val, False)}

        if self.layer.name() in self.dico_layer_attrval:
            self.dico_layer_attrval[self.layer.name()] = [
                item for item in self.dico_layer_attrval[self.layer.name()]
                if (item.get("sous_type"), item.get("valeur")) not in champ_attr_a_suppr
            ]

        for val in valeurs:
            # Vérifie si le tuple (sous_type, valeur) existe déjà dans les dict
            exists = any(
                item.get("sous_type") == sstype and item.get("valeur") == val
                for item in self.dico_layer_attrval[self.layer.name()]
            )
            if not exists:
                # Ajoute un dictionnaire complet avec valeurs par défaut
                self.dico_layer_attrval[self.layer.name()].append({
                    "sous_type": sstype,
                    "valeur": val,
                    "nom_btn": val,  # nom par défaut
                    "icon": "",
                    "autre_valeur": {}
                })

        # écriture du nouveau btn dans le json
        self.save_json()

        # sauvegarde des parametres (taille btn)
        self.save_json_parametres()

        self.clear_layout(self.layout_boutons)
        self.liste_filtres = []
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

    def save_json_parametres(self):
        taille_btn = int(self.dlg_sel_champ_val.lineEditTailleBtn.text())
        # Si le fichier n’existe pas → création directe
        if not os.path.exists(self.pathjsonparametre):
            elements = {"taille_des_boutons": taille_btn,
                        "taille_icone_dans_listview": 30}
            with open(self.pathjsonparametre, "w", encoding="utf-8") as f:
                json.dump(elements, f, ensure_ascii=False, indent=2)
            return

        # Si le fichier existe, on le charge et on met à jour les paramètres
        try:
            with open(self.pathjsonparametre, "r", encoding="utf-8") as f:
                data = json.load(f)
        except json.JSONDecodeError:
            data = {}

        # Conserve la valeur actuelle de "taille_icone_dans_listview" (sinon 30)
        taille_icone = data.get("taille_icone_dans_listview", 30)
        # Met à jour uniquement la taille des boutons
        data["taille_des_boutons"] = taille_btn
        data["taille_icone_dans_listview"] = taille_icone

        # sauvegarde
        with open(self.pathjsonparametre, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)


    def save_json(self):
        if not self.layer:
            return
        # Partir de l'ancien contenu si présent
        config = {}
        if os.path.exists(self.pathjson):
            try:
                with open(self.pathjson, "r", encoding="utf-8") as f:
                    config = json.load(f)
            except json.JSONDecodeError:
                print("Fichier JSON corrompu, un nouveau sera créé.")
                config = {}
        elements = []

        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            sous_type = item.get("sous_type")
            valeur = item.get("valeur")
            nom_btn = item.get("nom_btn", "")
            icon = item.get("icon", "")
            autre_valeur = item.get("autre_valeur", {})

            elements.append({
                "sous_type": sous_type,
                "valeur": valeur,
                "nom_btn": nom_btn,
                "icon": icon,
                "autre_valeur": autre_valeur
            })

        # Mettre à jour seulement la couche courante
        config[self.layer.name()] = elements

        # Sauvegarde sur disque
        try:
            with open(self.pathjson, "w", encoding="utf-8") as f:
                json.dump(config, f, ensure_ascii=False, indent=2)
        except Exception as e:
            print(f"Erreur lors de la sauvegarde JSON : {e}")

    def load_json_parametre(self):
        print("load_json_parametre")
        if os.path.exists(self.pathjsonparametre):
            try:
                with open(self.pathjsonparametre, "r") as f:
                    params = json.load(f)
            except (json.JSONDecodeError,OSError):
                print("Erreur lors du chargement du fichier JSON — contenu invalide.")
                params = {}
            self.taille_btn = params.get("taille_des_boutons",30) # 30 → valeur par défaut
            self.taille_icone_dans_listview = params.get("taille_icone_dans_listview",30)
            self.dlg_sel_champ_val.lineEditTailleBtn.setText(str(self.taille_btn))
        else:
            print("Le fichier de paramètres JSON n'existe pas.")
            # Valeur par défaut si le fichier n’existe pas
            self.taille_btn = 45
            self.taille_icone_dans_listview = 30
            self.dlg_sel_champ_val.lineEditTailleBtn.setText(str(self.taille_btn))


    def load_json(self):
        if os.path.exists(self.pathjson):
            with open(self.pathjson, "r", encoding="utf-8") as f:
                data = json.load(f)
        else:
            print("Le fichier de configuration des boutons JSON n'existe pas.")
            return

        #  si on récupère bien un dictionnaire issu du json
        if not isinstance(data, dict):
            print("Format JSON incorrect : ce doit être un dictionnaire")
            return

        for layer_name, elements in data.items():
            if not isinstance(elements, list):
                print(f"La valeur pour {layer_name} n’est pas une liste.")
                continue

            cleaned_elements = []
            for item in elements:
                if not isinstance(item, dict):
                    print(f"Élément inattendu dans {layer_name} : {item}")
                    continue

                # On récupère proprement tous les champs attendus
                sous_type = item.get("sous_type", "")
                valeur = item.get("valeur", "")
                nom_btn = item.get("nom_btn", "")
                icon = item.get("icon", "")
                autre_valeur = item.get("autre_valeur", {}) or {}

                # On reconstruit un dict cohérent
                cleaned_item = {
                    "sous_type": sous_type,
                    "valeur": valeur,
                    "nom_btn": nom_btn,
                    "icon": icon,
                    "autre_valeur": autre_valeur
                }
                cleaned_elements.append(cleaned_item)

            # On stocke la liste d’éléments nettoyés dans le dico principal
            self.dico_layer_attrval[layer_name] = cleaned_elements

    def clic_btn(self,val,champ_courant):
        print(f"CLIC BOUTON ,champ courant - val = {champ_courant}-{val}")
        self.layer.startEditing()
        # changement : champs-valeur du bouton sélectionné
        id_champ = self.layer.fields().indexFromName(champ_courant)
        for sel in self.layer.selectedFeatures():
            self.layer.changeAttributeValue(sel.id(), id_champ,val)

        # changement : champs-valeur des autres champ-valeur
        # tooltip = self.clicked_button.toolTip()
        # sstype, valeur = tooltip.split(SEPARATION_TOOLTIP)
        autre_sstype_valeur = {}
        # parcourt du dico pour isoler le dictionnaire des sstype_valeur à modifier
        for item in self.dico_layer_attrval.get(self.layer.name(), []):
            if item.get("sous_type") == champ_courant and item.get("valeur") == val:
                # Exemple : mise à jour du nom du bouton
                autre_sstype_valeur = item["autre_valeur"]
                break
        # changement d'attributs dans le layer
        for sel in self.layer.selectedFeatures():
            for champ,valeur in autre_sstype_valeur.items():
                id_champ = self.layer.fields().indexFromName(champ)
                self.layer.changeAttributeValue(sel.id(),id_champ,valeur)

    def on_active_layer_changed(self,layer):
        # print("on_active_layer_changed")
        if not layer:
            self.layer = None
            return
        self.layer = layer

        JeuxAttributs.clear_layout(self.layout_boutons)
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

    def initGui(self):
        pass

    def unload(self):
        try:
            self.iface.layerTreeView().currentLayerChanged.disconnect(self.on_active_layer_changed)
        except TypeError:
            pass  # déjà déconnecté

    def run(self):
        print("run")
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False

        # libère références Python aux anciennes UI (si elles existent)
        self.dlg = None
        self.dlg_sel_champ_val = None
        self.layout_boutons = None
        self.liste_filtres = []

        # chargement des ui
        self.dlg_sel_champ_val = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_widgets.ui"), self.dlg_sel_champ_val)
        self.dlg_sel_champ_val_AUTRE = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "choix_widgets.ui"), self.dlg_sel_champ_val_AUTRE)
        self.dlg_config_btn = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "conf_btn.ui"), self.dlg_config_btn)

        # connexion des slots : self.dlg_sel_champ_val
        self.dlg_sel_champ_val.pushButtonOk.clicked.connect(self.actualise_btn)
        self.dlg_sel_champ_val.comboBoxchamps.currentTextChanged.connect(
            lambda: self.change_champ(self.dlg_sel_champ_val))
        self.dlg_sel_champ_val_AUTRE.comboBoxchamps.currentTextChanged.connect(
            lambda: self.change_champ(self.dlg_sel_champ_val_AUTRE))
        self.dlg_sel_champ_val_AUTRE.pushButtonOk.clicked.connect(self.actualise_autre_val)

        # connexion des slots : self.dlg_config_btn
        self.dlg_config_btn.pushButtonDeplacer.clicked.connect(self.deplace_btn)
        # gestion de la suppression de la ligne sélectionnée (valeur autre)
        self.dlg_config_btn.pushButton_suppr_row.clicked.connect(self.suppr_ligne_tableview)
        self.dlg_config_btn.pushButtonOk.clicked.connect(
            lambda: self.valide_config_btn(self.sstype_btn_sel, self.valeur_btn_sel))
        self.dlg_config_btn.pushButton_choix_autre_valeur.clicked.connect(self.choix_autre_valeur)
        self.dlg_config_btn.spinBoxPosition.valueChanged.connect(self.spinbox_change)

        self.inittableview_autre_valeur()

        # show the dialog
        self.dlg = QDialog()
        self.dlg.setWindowTitle("Jeux d'attributs")
        self.dlg.setWindowIcon(QIcon(os.path.join(os.path.dirname(__file__),"icons" ,"icon_principal.png")))
        self.dlg.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)

        self.layer = self.iface.activeLayer()
        self.layout_boutons = LayoutFluide(self.dlg)
        self.load_json_parametre() # a faire AVANT init layout
        self.initLayout()
        self.load_json()
        self.ajout_btn_from_json()

        # EVENEMENT DE CHANGEMENT DE LAYER ACTIF
        # s'assurer de ne pas connecter plusieurs fois, mais juste 1 fois
        try:
            self.iface.layerTreeView().currentLayerChanged.disconnect(self.on_active_layer_changed)
        except TypeError:
            pass
        self.iface.layerTreeView().currentLayerChanged.connect(self.on_active_layer_changed)

        self.dlg.show()

