# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassPlugin
                                 A QGIS plugin
 plugin generique
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Gérôme PECHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QCheckBox
from qgis._core import QgsMapLayer
from qgis.core import QgsProject

# Initialize Qt resources from file resources.py

# Import the code for the dialog
# from .jeux_attributs_dialog import ClassPluginDialog
import os.path

from .main_dialog import MainDialog
from .symbologie import *
from .fonction import *
from .constante import *



class JeuxAttribut:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):

        # Save reference to the QGIS interface
        self.dlgAProposDe = None
        self.dlg = None
        self.iface = iface
        self.layer = None

        # TEST
        self.dico_filtre = {}

        self.plugin_dir = os.path.dirname(__file__)

    def add_all_widget(self):
        clear_layout(self.dlg.formlayout)
        dico_champ = get_champs(self.layer)

        for type,champs in dico_champ.items():
            for champ in champs:
                if champ not in self.dico_filtre:
                    continue
                valeurs_filtre = self.dico_filtre[champ]
                if type == "ValueMap":
                    self.dlg.add_widget(champ, valeurs_filtre, "ValueMap")
                elif type == "TextEdit":
                    self.dlg.add_widget(champ, valeurs_filtre, "TextEdit")
                elif type == "DateTime":
                    self.dlg.add_widget(champ, valeurs_filtre, "DateTime")

        self.dlg.adjustSize()
        self.dlg.setFixedSize(self.dlg.sizeHint())


    # retourne les champs en fonction de leur type
    def get_champs_by_type(self, type):
        """Retourne la liste des champs pour un type d'éditeur donné."""
        list_champs = []
        for field in self.layer.fields():
            index = self.layer.fields().indexOf(field.name())
            if self.get_type_champ(index) == type:
                list_champs.append(field.name())
        return list_champs


    def get_type_champ(self,index):
        return self.layer.editorWidgetSetup(index).type()


    def on_layer_changed(self,layer):
        self.layer = layer

        # le test parce que self.dlg n'existe pas encore , il est declaré apres on_layer_changed
        if self.dlg is None:
            return
        # mise a jour du layer pour le dialogue
        self.dlg.layer = layer

        # on vide le dico des widgets cliqués
        self.dlg.widget_clique.clear()

        # Recharger le filtre depuis le JSON du nouveau layer
        self.dico_filtre = loadjson(self.layer.name())
        if len(self.dico_filtre) == 0:
            self.dlg.btn_valider.setEnabled(False)
        else:
            self.dlg.btn_valider.setEnabled(True)

        # Synchroniser aussi avec le dialog principal
        self.dlg.dico_filtre = self.dico_filtre

        # clear_layout(self.dlg.formlayout)
        self.add_all_widget()

        # self.dlg.get_attributs_sel_unique()
        self.dlg.get_attributs_communs()

        # initialisation du nombre d'entités sélectionnées
        text = f"<b>Sélection = <span style ='color: red'> {self.layer.selectedFeatureCount()}</b></span>"
        self.dlg.label_nbsel.setText(text)

    def actualiserSelection(self):
        if self.dlg is None:
            return
        # initialisation du nombre d'entités sélectionnées
        nb_sel = self.layer.selectedFeatureCount()
        print("nb_sel = ",nb_sel)
        text = f"<b>Sélection = <span style ='color: red'> {nb_sel}</b></span>"
        self.dlg.label_nbsel.setText(text)

        if nb_sel == 0:
            self.dlg.btn_valider.setEnabled(False)
        else:
            self.dlg.btn_valider.setEnabled(True)

        # Remet la couleur par défaut pour tout les boutons ajoutés dynamiquement
        # et sauvegarde des valeurs des lineedit.
        for w in self.dlg.findChildren(QWidget):
            if w.property("iswidgetjson"):
                # Remet la couleur par défaut
                if isinstance(w, QLineEdit):
                    w.clear()
                    w.setStyleSheet("background-color: None")
                elif isinstance(w, QPushButton):
                    w.setStyleSheet("background-color: None")
                    # w.setStyleSheet("background-color: None")

                elif isinstance(w, QDateTimeEdit):
                    w.setStyleSheet("background-color: None")

                elif isinstance(w, QComboBox):
                    # combo
                    w.setStyleSheet("background-color: None")
                    model = w.model()
                    # items du combo
                    for i in range(model.rowCount()):
                        index = model.index(i, 0)
                        model.setData(index, QColor("white"), Qt.BackgroundRole)

        self.dlg.dico_val_linedit.clear()

        # on gère les attributs communs si plusieurs selections
        if nb_sel >0:
            self.dlg.get_attributs_communs()

    def apropos(self):
        self.dlgAProposDe.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.WindowCloseButtonHint)
        self.dlgAProposDe.exec_()

    def initGui(self):
        pass

    def unload(self):
        pass

    def run(self):

        # une seule instance de dialogue
        if self.dlg is not None:
            return

        # un projet doit être ouvert
        projet = QgsProject.instance()
        if len(projet.mapLayers()) <= 0:
            afficheerreur("Veuillez charger projet")
            return
        else:
            self.layer = self.iface.activeLayer()


        # on passe en paramètre "self.actualiserSelection" pour la réutiliser dans le main_dialog
        self.dlg = MainDialog(self.iface,self.layer,self)

        # initialisation de la treeview du filtre
        clear_layout(self.dlg.formlayout)
        self.dico_filtre = loadjson(self.layer.name())
        if len(self.dico_filtre) == 0:
            self.dlg.btn_valider.setEnabled(False)
        else:
            self.dlg.btn_valider.setEnabled(True)


        # ajout du nombre d'entités sélectionnées
        text = f"<b>Sélection = <span style ='color: red'> {self.layer.selectedFeatureCount()}</b></span>"
        self.dlg.label_nbsel.setText(text)

        # connexion di slot "chemin le plus court"
        self.dlg.btn_che_court.clicked.connect(self.dlg.che_plus_court)
        self.dlg.btn_che_court.setFocusPolicy(Qt.NoFocus)

        self.add_all_widget()
        self.dlg.get_attributs_communs()
        self.dlg.show()

        # deconnecter le signal avant de la reconnecter
        self.iface.mapCanvas().currentLayerChanged.connect(self.on_layer_changed)
        try:
            self.iface.mapCanvas().selectionChanged.disconnect(self.actualiserSelection)
        except TypeError:
            pass  # aucune connexion existante

        self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)
        self.actualiserSelection()
        # Run the dialog event loop
        result = self.dlg.exec_()
        if not result:
            # si on quitte on remet la vue sans le sens de numérisation
            suppr_symb_sens_num(self.layer)
            self.dlg.is_affiche_sens_num = False
            # on redessine la couche pour prend en compte du changement de style initial
            self.layer.triggerRepaint()
            # on reinitialise pour gere le rechargement si une seule instance
            self.dlg = None


