# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassPlugin
                                 A QGIS plugin
 plugin generique
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Gérôme PECHEUR
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# Import the code for the dialog
import os.path

from qgis.PyQt.QtWidgets import QApplication
from qgis.PyQt.QtCore import QSettings,QSize,QPoint
from qgis.PyQt.QtGui import QColor
from qgis.core import QgsProject,QgsApplication
from qgis.utils import plugins

from .main_dialog import MainDialog
from .fonction import *
from .constante import *



class JeuxAttribut:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):

        # Save reference to the QGIS interface
        self.dlgAProposDe = None
        self.dlg = None
        self.iface = iface
        self.layer = None

        self.dico_filtre = {}

        self.plugin_dir = os.path.dirname(__file__)

    def add_all_widget(self):
        clear_layout(self.dlg.formlayout)
        dico_champ = get_champs(self.layer)

        for type,champs in dico_champ.items():
            for champ in champs:
                if champ not in self.dico_filtre:
                    continue
                valeurs_filtre = self.dico_filtre[champ]
                if type == "ValueMap":
                    self.dlg.add_widget(champ, valeurs_filtre, "ValueMap")
                elif type == "TextEdit":
                    self.dlg.add_widget(champ, valeurs_filtre, "TextEdit")
                elif type == "DateTime":
                    self.dlg.add_widget(champ, valeurs_filtre, "DateTime")

        self.dlg.adjustSize()
        self.dlg.setFixedSize(self.dlg.sizeHint())


    # retourne les champs en fonction de leur type
    def get_champs_by_type(self, type):
        """Retourne la liste des champs pour un type d'éditeur donné."""
        list_champs = []
        for field in self.layer.fields():
            index = self.layer.fields().indexOf(field.name())
            if self.get_type_champ(index) == type:
                list_champs.append(field.name())
        return list_champs


    def get_type_champ(self,index):
        return self.layer.editorWidgetSetup(index).type()


    def on_layer_changed(self,layer):
        # ce n'est pas un layer mais un groupe de couche ou autre, on ne fait rien
        if layer is None:
            return
        self.layer = layer


        # le test parce que self.dlg n'existe pas encore, il est declaré apres on_layer_changed
        if self.dlg is None:
            return
        # mise à jour du layer pour le dialogue
        self.dlg.layer = layer

        # on vide le dico des widgets cliqués
        self.dlg.widget_clique.clear()

        # Recharger le filtre depuis le JSON du nouveau layer
        self.dico_filtre = loadjson(self.layer.name())
        if len(self.dico_filtre) == 0:
            self.dlg.btn_valider.setEnabled(False)
        else:
            self.dlg.btn_valider.setEnabled(True)

        # Synchroniser aussi avec le dialog principal
        self.dlg.dico_filtre = self.dico_filtre

        # clear_layout(self.dlg.formlayout)
        self.add_all_widget()

        # self.dlg.get_attributs_sel_unique()
        self.dlg.get_attributs_communs()

        # initialisation du nombre d'entités sélectionnées
        text = f"<b>Sélection = <span style ='color: red'> {self.layer.selectedFeatureCount()}</b></span>"
        self.dlg.label_nbsel.setText(text)

    def actualiserSelection(self):
        if self.dlg is None:
            return
        self.dlg.get_attributs_communs()
        # initialisation du nombre d'entités sélectionnées
        nb_sel = self.layer.selectedFeatureCount()
        text = f"<b>Sélection = <span style ='color: red'> {nb_sel}</b></span>"
        self.dlg.label_nbsel.setText(text)

        if nb_sel == 0:
            self.dlg.btn_valider.setEnabled(False)
            # TODO : a faire : mettre les dates a 1900....
        else:
            self.dlg.btn_valider.setEnabled(True)

        # Remet la couleur par défaut pour tous les boutons ajoutés dynamiquement
        # et sauvegarde des valeurs des lineedit.
        for w in self.dlg.findChildren(QWidget):
            if w.property("iswidgetjson"):
                # Remet la couleur par défaut
                if isinstance(w, QLineEdit):
                    w.clear()
                    w.setStyleSheet("background-color: None")
                elif isinstance(w, QPushButton):
                    w.setStyleSheet("background-color: None")

                # elif isinstance(w, QDateEdit):
                elif isinstance(w, QgsDateTimeEdit):
                    w.setStyleSheet("background-color: None")
                    # w.setDateTime(QDateTime(QDate(1900, 1, 1)))
                    w.setNullRepresentation("Pas de date")

                elif isinstance(w, QComboBox):
                    # combo
                    w.setStyleSheet("background-color: None")
                    model = w.model()
                    # items du combo
                    for i in range(model.rowCount()):
                        index = model.index(i, 0)
                        model.setData(index, QColor("white"), BackgroundRole)

        self.dlg.dico_val_linedit.clear()

        # on gère les attributs communs si au moins une selection
        if nb_sel >0:
            self.dlg.get_attributs_communs()

    def apropos(self):
        self.dlgAProposDe.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        self.dlgAProposDe.exec()

    def initGui(self):
        self.iface.projectRead.connect(self.on_project_opened)

    def unload(self):
        pass

    def sauve_position_dial(self):
        settings = QSettings(QSettings.NativeFormat, QSettings.UserScope,
                             "IGN", TITRE)
        settings.setValue("position", self.dlg.pos())
        settings.setValue("taille", self.dlg.size())
        settings.setValue("visible", self.dlg.isVisible())

    def restore_position_dial(self):
        settings = QSettings(QSettings.NativeFormat, QSettings.UserScope, "IGN", TITRE)
        pos = settings.value("position", type=QPoint)
        size = settings.value("taille", type=QSize)
        if pos is None:
            return
        screens = QApplication.screens()
        multi = len(screens) > 1
        # Vérifie si la position est sur un des écrans
        on_screen = any(screen.geometry().contains(pos) for screen in screens)
        if on_screen:
            self.dlg.move(pos)
            if size:
                self.dlg.resize(size)
        else:
            # Si un seul écran → replacer en haut-gauche
            if not multi:
                self.dlg.move(QPoint(0, 0))
            else:
                # Multi-écran mais position invalide → centrer sur écran principal
                primary = QApplication.primaryScreen().geometry()
                center = primary.center()
                self.dlg.move(center - self.dlg.rect().center())

    def on_project_opened(self):
        settings = QSettings(QSettings.NativeFormat, QSettings.UserScope, "IGN", TITRE)
        visible = settings.value("visible", False, type=bool)

        if visible:
            self.run()

    def on_dialog_closed(self):
        self.sauve_position_dial()
        # déconnexion des signaux
        try:
            self.iface.mapCanvas().selectionChanged.disconnect(self.actualiserSelection)
        except TypeError:
            pass
        try:
            self.iface.currentLayerChanged.disconnect(self.actualiserSelection)
        except TypeError:
            pass
        # si on quitte, on remet la vue sans le sens de numérisation via le plugin
        try:
            processing_plugin = plugins[PLUGIN_CHE_SENS_NUM]
            processing_plugin.suppr_symb_sens_num(self.layer)
        except:
            pass
        self.dlg = None

    def fermeture_qgis(self):
        self.sauve_position_dial()

    def run(self):
        # une seule instance de dialogue
        if self.dlg is not None:
            return

        # un projet doit être ouvert
        projet = QgsProject.instance()
        if len(projet.mapLayers()) <= 0:
            afficheerreur("Veuillez charger projet")
            return
        else:
            self.layer = self.iface.activeLayer()

        self.dlg = MainDialog(self.iface,self.layer,self,parent = self.iface.mainWindow())

        # événement fermeture de qgis
        QgsApplication.instance().aboutToQuit.connect(self.fermeture_qgis)
        self.restore_position_dial()

        # connection de la fermeture du dialogue
        self.dlg.finished.connect(self.on_dialog_closed)

        # initialisation de la treeview du filtre
        clear_layout(self.dlg.formlayout)
        self.dico_filtre = loadjson(self.layer.name())
        if len(self.dico_filtre) == 0:
            self.dlg.btn_valider.setEnabled(False)
        else:
            self.dlg.btn_valider.setEnabled(True)

        # ajout du nombre d'entités sélectionnées
        text = f"<b>Sélection = <span style ='color: red'> {self.layer.selectedFeatureCount()}</b></span>"
        self.dlg.label_nbsel.setText(text)

        # connexion di slot "chemin le plus court"
        self.dlg.btn_che_court.clicked.connect(self.dlg.che_plus_court)
        self.dlg.btn_che_court.setFocusPolicy(NoFocus)

        self.add_all_widget()
        self.dlg.get_attributs_communs()
        self.dlg.show()

        self.iface.mapCanvas().currentLayerChanged.connect(self.on_layer_changed)

        self.iface.mapCanvas().selectionChanged.connect(self.actualiserSelection)
        self.actualiserSelection()
        # Run the dialog event loop
        # result = self.dlg.exec()
        # if not result:
        #     # sauvegarde de la position du dial dans la base de registre
        #     self.sauve_position_dial()
        #     # on deconnecte le signal en quittant
        #     try:
        #         self.iface.mapCanvas().selectionChanged.disconnect(self.actualiserSelection)
        #     except TypeError:
        #         pass  # aucune connexion existante
        #     # si on quitte, on remet la vue sans le sens de numérisation via le plugin
        #     try:
        #         processing_plugin = plugins[PLUGIN_CHE_SENS_NUM]
        #         processing_plugin.suppr_symb_sens_num(self.layer)
        #     except:
        #         pass
        #
        #     # on redessine la couche pour prendre en compte du changement de style initial
        #     self.layer.triggerRepaint()
        #     # on réinitialise pour gere le rechargement si une seule instance
        #     self.dlg = None


